#version: '3'

services:
  web:
    image: chalanpro:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - chalan-network

  redis:
    image: redis:7.4-alpine
    networks:
      - chalan-network

networks:
  chalan-network:

volumes:
  mysql-data:
