# Generated by Django 5.0.3 on 2025-07-01 02:44

import appidentity.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appidentity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=appidentity.utils.logo_upload_path),
        ),
    ]
