"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from corsheaders.defaults import default_headers
from pathlib import Path
from corsheaders.defaults import default_headers
import os
import logging 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zf^1c+5%cj8m5k%^1(5c06e79xo81tgsapvcp1y6n7o74_q_$#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'auditapp',
    'ctrctsapp',
    'crewsapp',
]

MIDDLEWARE = [
    'project.DisableCSRF.DisableCSRF',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Si usas sesiones de autenticación (en lugar de TokenAuthentication), habilita CSRF
CSRF_TRUSTED_ORIGINS = ['http://localhost:8080']  # Dominio del frontend

# Permitir todas las solicitudes desde el frontend
CORS_ALLOW_ALL_ORIGINS = True  # Para desarrollo, en producción deberías limitar a dominios específicos

CORS_ALLOW_CREDENTIALS = True

# Importar default_headers

#CORS_ALLOWED_ORIGINS = [
#    'https://example.com',
#    'https://sub.example.com',
#    'http://localhost:8080',
#    'http://127.0.0.1:8080',
#    'http://192.168.0.248:8080',
#    'http://localhost:8080',
#    'http://localhost:8000',
#]



# Permite todos los encabezados CORS estándar
CORS_ALLOW_HEADERS = list(default_headers) + [
    'access-control-allow-origin',
    'X-Custom-Header',
    'X-Requested-With',
    'Authorization',
    'Content-Type'
]

CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
)

REST_FRAMEWORK = {
    # Definir las clases de autenticación por defecto
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  # Autenticación con tokens
    ],
    
    # Clases de permisos por defecto (esto afecta las vistas por defecto de DRF)
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Requiere autenticación en todas las vistas
    ],
    
    # Otras configuraciones útiles para DRF

}

# Asegurarse de que se está utilizando el modelo de usuarios predeterminado de Django
AUTH_USER_MODEL = 'auth.User'

# Usar el backend de permisos de Django
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Backend de autenticación estándar de Django
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'chalan_admin',
        'USER': 'oliver', 
        'PASSWORD': '13694344Om$',
        'HOST': 'localhost',
        'PORT': '3306',     
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

logger = logging.getLogger('django.db.backends')
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler())

# Configuración para el envío de correos electrónicos
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.tu_proveedor.com'  # Cambia esto por tu proveedor de SMTP
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'tu_email@tu_dominio.com'  # Cambia esto por tu email
EMAIL_HOST_PASSWORD = 'tu_contraseña'  # Cambia esto por tu contraseña

# URL para el restablecimiento de contraseña
PASSWORD_RESET_TIMEOUT = 14400  # 4 horas