# Generated by Django 5.0.3 on 2025-04-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManualEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('module', models.CharField(help_text='Ej: Inventario, ERP, Contratos', max_length=100)),
                ('summary', models.TextField(blank=True, help_text='Resumen corto para vista previa o meta descripción.')),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manual Entry',
                'verbose_name_plural': 'Manual Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
