# Generated by Django 5.0.3 on 2025-08-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptransactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partytype',
            options={'ordering': ['name'], 'verbose_name': 'Party Type', 'verbose_name_plural': 'Party Types'},
        ),
        migrations.AddField(
            model_name='partytype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partytype',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
