# Generated by Django 5.0.3 on 2025-11-24 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crewsapp', '0001_initial'),
        ('ctrctsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='crews', to='ctrctsapp.job', verbose_name='Assigned Jobs'),
        ),
        migrations.AddField(
            model_name='crew',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='crews', to=settings.AUTH_USER_MODEL, verbose_name='Crew Members'),
        ),
        migrations.AddField(
            model_name='truckassignment',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crewsapp.crew', verbose_name='Assigned Crew'),
        ),
        migrations.AddField(
            model_name='truckassignment',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crewsapp.truck', verbose_name='Assigned Truck'),
        ),
    ]
