# Generated by Django 5.0.3 on 2025-11-12 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appinventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together={('product', 'price_type', 'unit', 'is_purchase', 'is_sale', 'valid_from', 'valid_until')},
        ),
    ]
