# Generated by Django 5.0.3 on 2025-04-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasure',
            name='conversion_sign',
            field=models.CharField(choices=[('ref', 'Reference Unit'), ('*', 'Smaller than reference'), ('/', 'Greater than reference')], default='ref', max_length=4),
        ),
    ]
