# Generated by Django 5.0.3 on 2025-04-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinventory', '0002_alter_unitofmeasure_conversion_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasure',
            name='conversion_sign',
            field=models.CharField(choices=[('ref', 'Reference Unit'), ('*', 'Smaller than reference (*)'), ('/', 'Greater than reference (/)')], default='ref', max_length=4),
        ),
    ]
