# Generated by Django 5.0.3 on 2025-07-13 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appinventory', '0003_alter_unitofmeasure_conversion_sign'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together={('product', 'price_type', 'unit', 'valid_from', 'valid_until')},
        ),
    ]
