# Generated by Django 5.0.3 on 2025-07-13 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appinventory', '0004_alter_productprice_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productunit',
            unique_together=set(),
        ),
    ]
