# Generated by Django 5.0.3 on 2025-07-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinventory', '0005_alter_productunit_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ProductUnit',
        ),
    ]
