# Generated by Django 5.0.3 on 2025-07-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinventory', '0006_productprice_is_sale_delete_productunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='is_purchase',
            field=models.BooleanField(default=False),
        ),
    ]
